image: maven:latest

cache:
  paths:
    - .m2/repository/
    - target/

stages:
  - test-server
  - build-server
  - deploy-heroku-staging-server

# test stage will compile the code and run all the unit tests present in the
# test folder.
test:
  stage: test-server
  tags:
    - ugrad
  script:
    - cd server
    - mvn verify
  artifacts:
    when: always
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/failsafe-reports/TEST-*.xml
    
# build stage will just build the codebase without running
# any tests or creating any jar file.
build:
  stage: build-server
  tags:
    - ugrad
  script:
    - cd server
    - mvn clean package -DskipTests=true
    - ls
  artifacts:
    paths:
       - target/*.jar


## deploy stage will create package the jar and keep it in the target folder.
## The success of deploy stage will mark the pipeline as passed.
deploy:
  stage: deploy-heroku-staging-server
  image: ruby:latest
  tags:
    - dalfcs_docker_autoscale  
  before_script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
  script:
    - dpl --provider=heroku --app=$HARSH_HEROKU_APP_NAME_STAGING --api-key=$HARSH_HEROKU_API_KEY

